version: "2"

services:
  www:
    image: nginx
    volumes:
    - .:/usr/share/nginx/html
    ports:
    - 80
  builder:
    build: .
    volumes:
    - ..:/repo
    working_dir: /repo/slides
    environment:
      - REPOSITORY_URL=https://github.com/marcianomoreno/container.training
    command: ./build.sh forever

